# Generated by Django 4.0 on 2025-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_slug_alter_product_slug'),
        ('accounts', '0002_user_is_verify_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='shop.Product'),
        ),
    ]
