# Generated by Django 4.0 on 2025-03-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verify_alter_user_is_active'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='one', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default='09', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(default='37181', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user'),
        ),
    ]
